### ISSUE TITLE
[feature] Adding the CVSS/CVE score

### ISSUE THREAD

**Issue by knabben** [guacsec/guac#1072]
**Is your feature request related to a problem? Please describe.**
The default graphql schema `CertifyVuln` do not contain any information related to CVSS or score  (it exists only in the scorecard).

**Describe the solution you'd like**
I would like to access this information in the vulnerability field or even a related `score` mapping. 

```
    vulnerability {
      __typename
      ... on CVE {
        id
        year
        cveId
        score // new cvss field
        severity // new cvss field
      }
```

**Describe alternatives you've considered**
Having the score for filtering and enumerating the CVEs is a fundamental requirement

**Comment by lumjjb** [comment]
Hmm i think in this case since score and severity are values that change and may have different values from different sources, perhaps a VulnerabilityMetadata node with these fields would be fitting here.

CVEs data type is considered immutable in our model, so there are potentially different values at different times or from different sources, it would not work with the current way CVE nodes are used.

**Comment by pxp928** [comment]
+1 to the VulnerabilityMetadata node that can link to vulnerabilities nodes.

```
enum CVSSSeverity {
  NONE
  LOW
  MEDIUM
  HIGH
  CRITICAL
}

type VulnerabilityMetadata {
  id: ID!
  score: Float!
  severity: CVSSSeverity!
  origin: String!
  collector: String!
}
```

Any other fields that might be worth capturing?

**Comment by lumjjb** [comment]
nit:   timeStamp instead of timeScanned, since it is technically not a scan.

Also, i think there's both CVSS 2.0 and 3.0, these should be separate fields and optional in case it is not present. 

I'd also be in favor for a additionalInformation field which is text string if there's any other information, as well as a `links []string` to point to other resources.

**Comment by pxp928** [comment]
```
type VulnerabilityMetadata {
  id: ID!
  vulnerability: Vulnerability!
  "optional cvss 2.0 score"
  cvss2.0Score: Float
  "optional cvss 3.0 score"
  cvss3.0Score: Float
  timeStamp: Time!
  additionalInformation: String!
  "Pointing to other resources"
  links: [String!]
  origin: String!
  collector: String!
}
```

Agree about the severity: that can be calculated post-process depending on the CVSS version that is used. @mihaimaruseac @mlieberman85 Thoughts?

**Comment by mlieberman85** [comment]
I wonder if it's worthwhile to separate out cvss from some of the metadata into its own node? I just worry about having a place where we're dumping whatever into this where most of it is optional and it can be difficult to sort out.

**Comment by pxp928** [comment]
true. Same for the scores and they would default to nothing. Updating the above to capture this.

**Comment by knabben** [comment]
Thanks! I will open a PR and we follow the discussions from there

**Comment by pxp928** [comment]
@knabben Based on chatting more on this issue, it was decided that we should move `score` into its own node type and remove `links` and `additionalInformation`. I will update the issue once we get some more consensus on the node definitions.

**Comment by pxp928** [comment]
- VulnerabilityMetadata node (one-to-one mapping to score). Mapping to vulnerability ID node
  - remove additional information and links
  - put a timestamp on the edge property
  - score node
    - score type enum
    - score string
