### ISSUE TITLE
A case for "has-a" relationship edge

### ISSUE THREAD

**Issue by nadgowdas** [guacsec/guac#156]
This issue is created to collect feedback/ideas on extending feature supports for nodes in the graph:

Currently, guac support following edges:
-  ContainsEdge : Contains is an edge that represents the fact that an `PackageNode` contains a `ArtifactNode`
- DependsOnEdge: DependsOnEdge is an edge that represents the fact that an `ArtifactNode/PackageNode` depends on another `ArtifactNode/PackageNode`
- BuiltByEdge: BuiltByEdge is an edge that represents the fact that an `ArtifactNode` has been built by a `BuilderNode`
- AttestationForEdge: AttestationForEdge is an edge that represents the fact that an  `AttestationNode` is an attestation for an `ArtifactNode`.
- IdentityForEdge: IdentityForEdge is an edge that represents the fact that an `IdentityNode` is an identity for an `AttestationNode`.

In addition to these, a node can have additional properties ( e.g. a package node can have License, Vulnerabilities, etc.) 

 a new "has-a" relationship can help to support such extensible properties for nodes.

**Comment by jchestershopify** [comment]
I disagree. If we want to add new properties to the model, they should be added to the model in terms of the database primitives. Adding a database within a database is an anti-pattern.

**Comment by lumjjb** [comment]
Hmm @nadgowdas , we recently added the `MetadataFor` relationship, do you think that will be able to capture at least on an abstract level the data fields you are thinking about? (see https://github.com/guacsec/guac/pull/130). The idea here would be that there would be metadata, and that could be linked back to an attestation.. If you see the metadata type, it is a unstructured type with a "type" field as a key to make meaningful deduction about the fields within.

We have another discussion on creating convenience labels for each of them, but the idea needs to be fleshed out a bit more due to it introducing a whole set of guarantees for making something specific first-class. Opened an issue to discuss this more: https://github.com/guacsec/guac/issues/165
