### ISSUE TITLE
Is it possible to use a non GPL db?

### ISSUE THREAD

**Issue by anoop2811** [guacsec/guac#194]
We have a hard requirement to not use GPL software, it is possible to use a different graph db like ArangoDB which has an Apache license?

**Comment by tomthebuzz** [comment]
Would also be interested to add a non Neo4J DB of various flavors (no specific preference as long as FOSS license is available).

**Comment by lumjjb** [comment]
Yup it should be possible to do that! Currently we are doing this with neo4j due to familiarity and availability of the GCP marketplace to run the service. If folks have suggestions and would like to work on it, please do put them here and we can explore what would work! Contributions much welcome! We do have an[ interface for the assembler (the graph DB portion)](https://github.com/guacsec/guac/blob/main/pkg/assembler/nodes.go), and so as long as these can be translated to the creation queries of another DB, it should work seamlessly.
