### ISSUE TITLE
Node expansion collector (parser request for more data with collector subscription)

### ISSUE THREAD

**Issue by mihaimaruseac** [guacsec/guac#244]
In GUAC might have ingested nodes which contain references to artifact/package nodes/identifiers that the current populated GUAC database lacks metadata on - for example ingesting an SBOM with references to a PURL or github repo in which the collectors have not been configured to collect.

In this case, we want GUAC to be able to be intentional with seeking out information from configured sources/collectors to download this information. e.g., a private guac instance querying about the public one, or private GUAC instance upon seeing a PURL, to query deps.dev to ingest additional metadata.

Requirement

We need a mechanism to be able to fetch additional metadata to ingest into GUAC.
Augmenting the query protocol to handle user interactions when answering these types of queries when there is no/partial information. (e.g. provide feedback to the user on lack of data, and potentially the status of retrieving additional metadata)

**Comment by lumjjb** [comment]
@mihaimaruseac 

Rewrote this to expand a bit more, if you think this reflect the intent, shall we replace the opening issue text?

In GUAC might have ingested nodes which contain references to artifact/package nodes/identifiers that the current populated GUAC database lacks metadata on - for example ingesting an SBOM with references to a PURL or github repo in which the collectors have not been configured to collect. 

In this case, we want GUAC to be able to be intentional with seeking out information from configured sources/collectors to download this information. e.g., a private guac instance querying about the public one, or private GUAC instance upon seeing a PURL, to query deps.dev to ingest additional metadata.

**Requirement**

1. We need a mechanism to be able to fetch additional metadata to ingest into GUAC. 
2. Augmenting the query protocol to handle user interactions when answering these types of queries when there is no/partial information. (e.g. provide feedback to the user on lack of data, and potentially the status of retrieving additional metadata)

**Comment by mihaimaruseac** [comment]
This sounds great!

I wasn't thinking of user-in-the-loop, but actually that's also a nicer addition

**Comment by lumjjb** [comment]
Wrote up a draft design for discussion

**Comment by JonZeolla** [comment]
Left some feedback in the design doc

**Comment by lumjjb** [comment]
Partially addressed by #306

**Comment by pxp928** [comment]
Collector subscriber work completed for the beta. Ability to collect more information from git repos, OCI registry and deps.dev
