### ISSUE TITLE
community: Is there a contributor ladder?

### ISSUE THREAD

**Issue by naveensrinivasan** [guacsec/guac#448]
# community: Is there a contributor ladder? 

Opening this to ask if there's a contributor ladder defined for this project.
Here's an example: https://github.com/kubernetes/community/blob/master/community-membership.md

Subtext: I'd be happy to help do PR review here, with the hopes of working towards maintainership, if there's a path for that :)

## Previous PRs

1. https://github.com/guacsec/guac/pull/436
2. https://github.com/guacsec/guac/pull/433
3. https://github.com/guacsec/guac/pull/415
4. https://github.com/guacsec/guac/pull/392
5. https://github.com/guacsec/guac/pull/386
6. https://github.com/guacsec/guac/pull/378
7. https://github.com/guacsec/guac/pull/377
8. https://github.com/guacsec/guac/pull/356
9. https://github.com/guacsec/guac/pull/351
10. https://github.com/guacsec/guac/pull/348
11. https://github.com/guacsec/guac/pull/338
12. https://github.com/guacsec/guac/pull/337
13. https://github.com/guacsec/guac/pull/335
14. https://github.com/guacsec/guac/pull/334
15. https://github.com/guacsec/guac/pull/330

## Open PRs 
1. https://github.com/guacsec/guac/pull/390
2. https://github.com/guacsec/guac/pull/406
3. https://github.com/guacsec/guac/pull/408
4. https://github.com/guacsec/guac/pull/409
5. https://github.com/guacsec/guac/pull/416
6. https://github.com/guacsec/guac/pull/434
7. https://github.com/guacsec/guac/pull/435
8. https://github.com/guacsec/guac/pull/437
9. https://github.com/guacsec/guac/pull/438
10. https://github.com/guacsec/guac/pull/446

## Issues opened
1. https://github.com/guacsec/guac/issues/331
2. https://github.com/guacsec/guac/issues/379
3. https://github.com/guacsec/guac/issues/407
4. https://github.com/guacsec/guac/issues/410
5. https://github.com/guacsec/guac/issues/439
6. https://github.com/guacsec/guac/issues/329
7. https://github.com/guacsec/guac/issues/336
8. https://github.com/guacsec/guac/issues/339
9. https://github.com/guacsec/guac/issues/350
10. https://github.com/guacsec/guac/issues/381

cc @lumjjb @pxp928 @mihaimaruseac @mlieberman85

**Comment by lumjjb** [comment]
Hi @naveensrinivasan ! Thanks for the contributions! I agree it will be good to have a structure there. On top of just having a group of maintainers, there will most likely be opportunities as well for other roles! 

At the moment, towards maintainership, we are looking for the following. Given that this is a fairly substantive list, we will be discussing some other roles would make it more accessible to a larger audience of OSS contributors.

- Development of features towards core GUAC functionality (collectors, parsers, graphQL, etc. towards current project goals)
- Show deep understanding of GUAC architecture, design, technical problems
- Show ability to resolve technical trade-offs and prioritize between features and technical debt
- Ability to commit to 2 weekly syncs (1 hour each) since we are moving at high velocity, we expect maintainers to be able to do the same
- Working well with majority of maintainers (currently based on a [maintainer quorum](https://github.com/guacsec/guac/blob/main/GOVERNANCE.md#maintainership)) 
- Ability to potentially sign an NDA to work with clients (optional)
