### ISSUE TITLE
Certifier just hangs.

### ISSUE THREAD

**Issue by justinabrahms** [guacsec/guac#568]
I'm on v1.0.0. When I run the certifier on my neo4j database, it hangs.

The contents of that database are 8260 package objects. There are no other types. Here's an example of it hanging for 1.5hrs before I killed it.

```
$ time bin/guacone certifier --gdbuser neo4j --gdbpass s3cr3t 
{"level":"info","ts":1678471088.764374,"caller":"cmd/root.go:94","msg":"Using config file: /Users/jabrahms/src/github.com/guacsec/guac/guac.yaml"}
^C
bin/guacone certifier --gdbuser neo4j --gdbpass s3cr3t  299.66s user 548.13s system 16% cpu 1:27:57.38 total
```

I attempted to take [the updated root_package.go](https://github.com/guacsec/guac/blob/main/pkg/certifier/components/root_package/root_package.go) from main, but the same thing happens.

**Comment by pxp928** [comment]
With the new re-architecture, this issue is resolved with the new query via graphQL in the [root_pacakage.go](https://github.com/guacsec/guac/blob/08f656c1b0258c16452d80d2efc2dccf4a5f8777/pkg/certifier/components/root_package/root_package.go).

Please re-open if another issue is encountered with the certifier.
